### ISSUE TITLE
Can you share the pre-trained desktop GPU latency predictor and FLOPS predictor?

### ISSUE THREAD

**Issue by auroua** [thomasccp/eagle#2]
To compare the performance of the binary relation predictor with our proposed predictor, can you share the pre-trained desktop GPU latency predictor and FLOPS predictor?

**Comment by vaenyr** [comment]
Hi, we've uploaded both predictors to the google drive. The latency predictor outputs normalised values so you will have to denormalise them using the following constants (they can be obtained from the provided dataset of desktop GPU latencies):
 - Max: 0.00951075005531311
 - Min: 0.0008091678619384765
We use a simple linear normalisation so you only need to scale by delta and add min.
Feel free to reopen the issue if you have any other questions/problems. :)
