### ISSUE TITLE
Number of devices

### ISSUE THREAD

**Issue by ruchtem** [thomasccp/eagle#3]
Hi guys,

thanks for the nice dataset. In the paper you report 6 devices, but in the readme you list 12 files.

1. How do they relate? Did you decide to just not use some?
2. What is the difference between `embedded-gpu-jetson-nono-fp16.pickle` and `embedded-gpu-jetson-nono-fp32.pickle`, i.e. what does `fp` stand for?

**Comment by thomasccp** [comment]
Hi @ruchtem ,

In the paper, we benchmark one device from each class of desktop CPU/GPU, embedded GPU/TPU and mobile GPU/DSP, hence 6 devices in total. The purpose is to illustrate that the latency correlation between classes of devices are not strongly correlated, which also indicates that having a dedicated latency dataset / predictor trained for each class of devices is necessary.

These are the devices reported in the paper:
- desktop-cpu-core-i7-7820x-fp32
- desktop-gpu-gtx-1080-ti-fp32
- embedded-gpu-jetson-nono-fp32
- embeeded-tpu-edgetpu-int8
- mobile-gpu-snapdragon-675-adren0-612-int8
- mobile-dsp-snapdragon-855-hexagon-690-int8

It is named as <class>-<model>-<precision>:
- fp32 means "single-precision floating-point" format occupying 32 bits.
- fp16 means "half-precision floating-point" format occupying 16 bits.
- int8 means a signed integer number stored with 8 bits.

We have been updating LatBench by adding more devices. After the paper is published we now have 13 devices in the dataset.

**Comment by ruchtem** [comment]
Great, thank you! Is the precision of both the input/feature maps and the weights?
